package ezpq

import "errors"

var (

	// Class 01 — Warning
	ErrWarning                          = errors.New("warning")
	ErrDynamicResultSetsReturned        = errors.New("dynamic_result_sets_returned")
	ErrImplicitZeroBitPadding           = errors.New("implicit_zero_bit_padding")
	ErrNullValueEliminatedInSetFunction = errors.New("null_value_eliminated_in_set_function")
	ErrPrivilegeNotGranted              = errors.New("privilege_not_granted")
	ErrPrivilegeNotRevoked              = errors.New("privilege_not_revoked")
	ErrStringDataRightTruncationWarn    = errors.New("string_data_right_truncation")
	ErrDeprecatedFeature                = errors.New("deprecated_feature")

	ErrNoData                                = errors.New("no_data")
	ErrNoAdditionalDynamicResultSetsReturned = errors.New("no_additional_dynamic_result_sets_returned")

	ErrSqlStatementNotYetComplete = errors.New("sql_statement_not_yet_complete")

	ErrConnectionException                           = errors.New("connection_exception")
	ErrConnectionDoesNotExist                        = errors.New("connection_does_not_exist")
	ErrConnectionFailure                             = errors.New("connection_failure")
	ErrSqlclientUnableToEstablishSqlconnection       = errors.New("sqlclient_unable_to_establish_sqlconnection")
	ErrSqlserverRejectedEstablishmentOfSqlconnection = errors.New("sqlserver_rejected_establishment_of_sqlconnection")
	ErrTransactionResolutionUnknown                  = errors.New("transaction_resolution_unknown")
	ErrProtocolViolation                             = errors.New("protocol_violation")

	ErrTriggeredActionException = errors.New("triggered_action_exception")

	ErrFeatureNotSupported = errors.New("feature_not_supported")

	ErrInvalidTransactionInitiation = errors.New("invalid_transaction_initiation")

	ErrLocatorException            = errors.New("locator_exception")
	ErrInvalidLocatorSpecification = errors.New("invalid_locator_specification")

	ErrInvalidGrantor        = errors.New("invalid_grantor")
	ErrInvalidGrantOperation = errors.New("invalid_grant_operation")

	ErrInvalidRoleSpecification = errors.New("invalid_role_specification")

	ErrDiagnosticsException                           = errors.New("diagnostics_exception")
	ErrStackedDiagnosticsAccessedWithoutActiveHandler = errors.New("stacked_diagnostics_accessed_without_active_handler")

	ErrCaseNotFound = errors.New("case_not_found")

	ErrCardinalityViolation = errors.New("cardinality_violation")

	ErrDataException                         = errors.New("data_exception")
	ErrArraySubscriptError                   = errors.New("array_subscript_error")
	ErrCharacterNotInRepertoire              = errors.New("character_not_in_repertoire")
	ErrDatetimeFieldOverflow                 = errors.New("datetime_field_overflow")
	ErrDivisionByZero                        = errors.New("division_by_zero")
	ErrErrorInAssignment                     = errors.New("error_in_assignment")
	ErrEscapeCharacterConflict               = errors.New("escape_character_conflict")
	ErrIndicatorOverflow                     = errors.New("indicator_overflow")
	ErrIntervalFieldOverflow                 = errors.New("interval_field_overflow")
	ErrInvalidArgumentForLogarithm           = errors.New("invalid_argument_for_logarithm")
	ErrInvalidArgumentForNtileFunction       = errors.New("invalid_argument_for_ntile_function")
	ErrInvalidArgumentForNthValueFunction    = errors.New("invalid_argument_for_nth_value_function")
	ErrInvalidArgumentForPowerFunction       = errors.New("invalid_argument_for_power_function")
	ErrInvalidArgumentForWidthBucketFunction = errors.New("invalid_argument_for_width_bucket_function")
	ErrInvalidCharacterValueForCast          = errors.New("invalid_character_value_for_cast")
	ErrInvalidDatetimeFormat                 = errors.New("invalid_datetime_format")
	ErrInvalidEscapeCharacter                = errors.New("invalid_escape_character")
	ErrInvalidEscapeOctet                    = errors.New("invalid_escape_octet")
	ErrInvalidEscapeSequence                 = errors.New("invalid_escape_sequence")
	ErrNonstandardUseOfEscapeCharacter       = errors.New("nonstandard_use_of_escape_character")
	ErrInvalidIndicatorParameterValue        = errors.New("invalid_indicator_parameter_value")
	ErrInvalidParameterValue                 = errors.New("invalid_parameter_value")
	ErrInvalidRegularExpression              = errors.New("invalid_regular_expression")
	ErrInvalidRowCountInLimitClause          = errors.New("invalid_row_count_in_limit_clause")
	ErrInvalidRowCountInResultOffsetClause   = errors.New("invalid_row_count_in_result_offset_clause")
	ErrInvalidTimeZoneDisplacementValue      = errors.New("invalid_time_zone_displacement_value")
	ErrInvalidUseOfEscapeCharacter           = errors.New("invalid_use_of_escape_character")
	ErrMostSpecificTypeMismatch              = errors.New("most_specific_type_mismatch")
	ErrDataExceptoinNullValueNotAllowed      = errors.New("null_value_not_allowed")
	ErrNullValueNoIndicatorParameter         = errors.New("null_value_no_indicator_parameter")
	ErrNumericValueOutOfRange                = errors.New("numeric_value_out_of_range")
	ErrStringDataLengthMismatch              = errors.New("string_data_length_mismatch")
	ErrStringDataRightTruncation             = errors.New("string_data_right_truncation")
	ErrSubstringError                        = errors.New("substring_error")
	ErrTrimError                             = errors.New("trim_error")
	ErrUnterminatedCString                   = errors.New("unterminated_c_string")
	ErrZeroLengthCharacterString             = errors.New("zero_length_character_string")
	ErrFloatingPointException                = errors.New("floating_point_exception")
	ErrInvalidTextRepresentation             = errors.New("invalid_text_representation")
	ErrInvalidBinaryRepresentation           = errors.New("invalid_binary_representation")
	ErrBadCopyFileFormat                     = errors.New("bad_copy_file_format")
	ErrUntranslatableCharacter               = errors.New("untranslatable_character")
	ErrNotAnXmlDocument                      = errors.New("not_an_xml_document")
	ErrInvalidXmlDocument                    = errors.New("invalid_xml_document")
	ErrInvalidXmlContent                     = errors.New("invalid_xml_content")
	ErrInvalidXmlComment                     = errors.New("invalid_xml_comment")
	ErrInvalidXmlProcessingInstruction       = errors.New("invalid_xml_processing_instruction")

	ErrIntegrityConstraintViolation = errors.New("integrity_constraint_violation")
	ErrRestrictViolation            = errors.New("restrict_violation")
	ErrNotNullViolation             = errors.New("not_null_violation")
	ErrForeignKeyViolation          = errors.New("foreign_key_violation")
	ErrUniqueViolation              = errors.New("unique_violation")
	ErrCheckViolation               = errors.New("check_violation")
	ErrExclusionViolation           = errors.New("exclusion_violation")

	ErrInvalidCursorState = errors.New("invalid_cursor_state")

	ErrInvalidTransactionState                         = errors.New("invalid_transaction_state")
	ErrActiveSqlTransaction                            = errors.New("active_sql_transaction")
	ErrBranchTransactionAlreadyActive                  = errors.New("branch_transaction_already_active")
	ErrHeldCursorRequiresSameIsolationLevel            = errors.New("held_cursor_requires_same_isolation_level")
	ErrInappropriateAccessModeForBranchTransaction     = errors.New("inappropriate_access_mode_for_branch_transaction")
	ErrInappropriateIsolationLevelForBranchTransaction = errors.New("inappropriate_isolation_level_for_branch_transaction")
	ErrNoActiveSqlTransactionForBranchTransaction      = errors.New("no_active_sql_transaction_for_branch_transaction")
	ErrReadOnlySqlTransaction                          = errors.New("read_only_sql_transaction")
	ErrSchemaAndDataStatementMixingNotSupported        = errors.New("schema_and_data_statement_mixing_not_supported")
	ErrNoActiveSqlTransaction                          = errors.New("no_active_sql_transaction")
	ErrInFailedSqlTransaction                          = errors.New("in_failed_sql_transaction")

	ErrInvalidSqlStatementName = errors.New("invalid_sql_statement_name")

	ErrTriggeredDataChangeViolation = errors.New("triggered_data_change_violation")

	ErrInvalidAuthorizationSpecification = errors.New("invalid_authorization_specification")
	ErrInvalidPassword                   = errors.New("invalid_password")

	ErrDependentPrivilegeDescriptorsStillExist = errors.New("dependent_privilege_descriptors_still_exist")
	ErrDependentObjectsStillExist              = errors.New("dependent_objects_still_exist")

	ErrInvalidTransactionTermination = errors.New("invalid_transaction_termination")

	ErrSqlRoutineException                       = errors.New("sql_routine_exception")
	ErrFunctionExecutedNoReturnStatement         = errors.New("function_executed_no_return_statement")
	ErrSQLRoutineModifyingSqlDataNotPermitted    = errors.New("modifying_sql_data_not_permitted")
	ErrSQLRoutineProhibitedSqlStatementAttempted = errors.New("prohibited_sql_statement_attempted")
	ErrSQLRoutineReadingSqlDataNotPermitted      = errors.New("reading_sql_data_not_permitted")

	ErrInvalidCursorName = errors.New("invalid_cursor_name")

	ErrExternalRoutineException                       = errors.New("external_routine_exception")
	ErrContainingSqlNotPermitted                      = errors.New("containing_sql_not_permitted")
	ErrExternalRoutineModifyingSqlDataNotPermitted    = errors.New("modifying_sql_data_not_permitted")
	ErrExternalRoutineProhibitedSqlStatementAttempted = errors.New("prohibited_sql_statement_attempted")
	ErrExternalRoutineReadingSqlDataNotPermitted      = errors.New("reading_sql_data_not_permitted")

	ErrExternalRoutineInvocationException = errors.New("external_routine_invocation_exception")
	ErrInvalidSqlstateReturned            = errors.New("invalid_sqlstate_returned")
	ErrExternalRoutineNullValueNotAllowed = errors.New("null_value_not_allowed")
	ErrTriggerProtocolViolated            = errors.New("trigger_protocol_violated")
	ErrSrfProtocolViolated                = errors.New("srf_protocol_violated")

	ErrSavepointException            = errors.New("savepoint_exception")
	ErrInvalidSavepointSpecification = errors.New("invalid_savepoint_specification")

	ErrInvalidCatalogName = errors.New("invalid_catalog_name")

	ErrInvalidSchemaName = errors.New("invalid_schema_name")

	ErrTransactionRollback                     = errors.New("transaction_rollback")
	ErrTransactionIntegrityConstraintViolation = errors.New("transaction_integrity_constraint_violation")
	ErrSerializationFailure                    = errors.New("serialization_failure")
	ErrStatementCompletionUnknown              = errors.New("statement_completion_unknown")
	ErrDeadlockDetected                        = errors.New("deadlock_detected")

	ErrSyntaxErrorOrAccessRuleViolation   = errors.New("syntax_error_or_access_rule_violation")
	ErrSyntaxError                        = errors.New("syntax_error")
	ErrInsufficientPrivilege              = errors.New("insufficient_privilege")
	ErrCannotCoerce                       = errors.New("cannot_coerce")
	ErrGroupingError                      = errors.New("grouping_error")
	ErrWindowingError                     = errors.New("windowing_error")
	ErrInvalidRecursion                   = errors.New("invalid_recursion")
	ErrInvalidForeignKey                  = errors.New("invalid_foreign_key")
	ErrInvalidName                        = errors.New("invalid_name")
	ErrNameTooLong                        = errors.New("name_too_long")
	ErrReservedName                       = errors.New("reserved_name")
	ErrDatatypeMismatch                   = errors.New("datatype_mismatch")
	ErrIndeterminateDatatype              = errors.New("indeterminate_datatype")
	ErrCollationMismatch                  = errors.New("collation_mismatch")
	ErrIndeterminateCollation             = errors.New("indeterminate_collation")
	ErrWrongObjectType                    = errors.New("wrong_object_type")
	ErrUndefinedColumn                    = errors.New("undefined_column")
	ErrUndefinedFunction                  = errors.New("undefined_function")
	ErrUndefinedTable                     = errors.New("undefined_table")
	ErrUndefinedParameter                 = errors.New("undefined_parameter")
	ErrUndefinedObject                    = errors.New("undefined_object")
	ErrDuplicateColumn                    = errors.New("duplicate_column")
	ErrDuplicateCursor                    = errors.New("duplicate_cursor")
	ErrDuplicateDatabase                  = errors.New("duplicate_database")
	ErrDuplicateFunction                  = errors.New("duplicate_function")
	ErrDuplicatePreparedStatement         = errors.New("duplicate_prepared_statement")
	ErrDuplicateSchema                    = errors.New("duplicate_schema")
	ErrDuplicateTable                     = errors.New("duplicate_table")
	ErrDuplicateAlias                     = errors.New("duplicate_alias")
	ErrDuplicateObject                    = errors.New("duplicate_object")
	ErrAmbiguousColumn                    = errors.New("ambiguous_column")
	ErrAmbiguousFunction                  = errors.New("ambiguous_function")
	ErrAmbiguousParameter                 = errors.New("ambiguous_parameter")
	ErrAmbiguousAlias                     = errors.New("ambiguous_alias")
	ErrInvalidColumnReference             = errors.New("invalid_column_reference")
	ErrInvalidColumnDefinition            = errors.New("invalid_column_definition")
	ErrInvalidCursorDefinition            = errors.New("invalid_cursor_definition")
	ErrInvalidDatabaseDefinition          = errors.New("invalid_database_definition")
	ErrInvalidFunctionDefinition          = errors.New("invalid_function_definition")
	ErrInvalidPreparedStatementDefinition = errors.New("invalid_prepared_statement_definition")
	ErrInvalidSchemaDefinition            = errors.New("invalid_schema_definition")
	ErrInvalidTableDefinition             = errors.New("invalid_table_definition")
	ErrInvalidObjectDefinition            = errors.New("invalid_object_definition")

	ErrWithCheckOptionViolation = errors.New("with_check_option_violation")

	ErrInsufficientResources      = errors.New("insufficient_resources")
	ErrDiskFull                   = errors.New("disk_full")
	ErrOutOfMemory                = errors.New("out_of_memory")
	ErrTooManyConnections         = errors.New("too_many_connections")
	ErrConfigurationLimitExceeded = errors.New("configuration_limit_exceeded")

	ErrProgramLimitExceeded = errors.New("program_limit_exceeded")
	ErrStatementTooComplex  = errors.New("statement_too_complex")
	ErrTooManyColumns       = errors.New("too_many_columns")
	ErrTooManyArguments     = errors.New("too_many_arguments")

	ErrObjectNotInPrerequisiteState = errors.New("object_not_in_prerequisite_state")
	ErrObjectInUse                  = errors.New("object_in_use")
	ErrCantChangeRuntimeParam       = errors.New("cant_change_runtime_param")
	ErrLockNotAvailable             = errors.New("lock_not_available")

	ErrOperatorIntervention = errors.New("operator_intervention")
	ErrQueryCanceled        = errors.New("query_canceled")
	ErrAdminShutdown        = errors.New("admin_shutdown")
	ErrCrashShutdown        = errors.New("crash_shutdown")
	ErrCannotConnectNow     = errors.New("cannot_connect_now")
	ErrDatabaseDropped      = errors.New("database_dropped")

	ErrSystemError   = errors.New("system_error")
	ErrIoError       = errors.New("io_error")
	ErrUndefinedFile = errors.New("undefined_file")
	ErrDuplicateFile = errors.New("duplicate_file")

	ErrConfigFileError = errors.New("config_file_error")
	ErrLockFileExists  = errors.New("lock_file_exists")

	ErrFdwError                             = errors.New("fdw_error")
	ErrFdwColumnNameNotFound                = errors.New("fdw_column_name_not_found")
	ErrFdwDynamicParameterValueNeeded       = errors.New("fdw_dynamic_parameter_value_needed")
	ErrFdwFunctionSequenceError             = errors.New("fdw_function_sequence_error")
	ErrFdwInconsistentDescriptorInformation = errors.New("fdw_inconsistent_descriptor_information")
	ErrFdwInvalidAttributeValue             = errors.New("fdw_invalid_attribute_value")
	ErrFdwInvalidColumnName                 = errors.New("fdw_invalid_column_name")
	ErrFdwInvalidColumnNumber               = errors.New("fdw_invalid_column_number")
	ErrFdwInvalidDataType                   = errors.New("fdw_invalid_data_type")
	ErrFdwInvalidDataTypeDescriptors        = errors.New("fdw_invalid_data_type_descriptors")
	ErrFdwInvalidDescriptorFieldIdentifier  = errors.New("fdw_invalid_descriptor_field_identifier")
	ErrFdwInvalidHandle                     = errors.New("fdw_invalid_handle")
	ErrFdwInvalidOptionIndex                = errors.New("fdw_invalid_option_index")
	ErrFdwInvalidOptionName                 = errors.New("fdw_invalid_option_name")
	ErrFdwInvalidStringLengthOrBufferLength = errors.New("fdw_invalid_string_length_or_buffer_length")
	ErrFdwInvalidStringFormat               = errors.New("fdw_invalid_string_format")
	ErrFdwInvalidUseOfNullPointer           = errors.New("fdw_invalid_use_of_null_pointer")
	ErrFdwTooManyHandles                    = errors.New("fdw_too_many_handles")
	ErrFdwOutOfMemory                       = errors.New("fdw_out_of_memory")
	ErrFdwNoSchemas                         = errors.New("fdw_no_schemas")
	ErrFdwOptionNameNotFound                = errors.New("fdw_option_name_not_found")
	ErrFdwReplyHandle                       = errors.New("fdw_reply_handle")
	ErrFdwSchemaNotFound                    = errors.New("fdw_schema_not_found")
	ErrFdwTableNotFound                     = errors.New("fdw_table_not_found")
	ErrFdwUnableToCreateExecution           = errors.New("fdw_unable_to_create_execution")
	ErrFdwUnableToCreateReply               = errors.New("fdw_unable_to_create_reply")
	ErrFdwUnableToEstablishConnection       = errors.New("fdw_unable_to_establish_connection")

	ErrPlpgsqlError   = errors.New("plpgsql_error")
	ErrRaiseException = errors.New("raise_exception")
	ErrNoDataFound    = errors.New("no_data_found")
	ErrTooManyRows    = errors.New("too_many_rows")

	ErrInternalError  = errors.New("internal_error")
	ErrDataCorrupted  = errors.New("data_corrupted")
	ErrIndexCorrupted = errors.New("index_corrupted")
)
